/* global define */
/*
---------------------------------
DECLARING AND ASSIGNING VARIABLES
--------------------------------- */

var masthead;
var slides;
var buttons;
var contents;
var container;
var i = 0;
var k;

/*
-----------------------
START CODING SLIDE-SHOW
----------------------- */

var masthead = document.querySelector(".mh-image");
    
var slides = [
    "<figure><img src=\"./img/geothermal.png\" alt\"geothermal-energy\"> <figcaption>Alternative Energy Source: Geothermal Energy</figcaption></figure>",
    "<figure><img src=\"./img/hydro.png\" alt\"hydro-energy\"> <figcaption>Alternative Energy Source: Hydroelectric Energy</figcaption></figure>",
    "<figure><img src=\"./img/nuclear.png\" alt\"nuclear-energy\"> <figcaption>Alternative Energy Source: Nuclear Energy</figcaption></figure>",
    "<figure><img src=\"./img/solar.png\" alt\"solar-energy\"> <figcaption>Alternative Energy Source: Solar Energy</figcaption></figure>",
    "<figure><img src=\"./img/wind-power.png\" alt\"wind-energy\"> <figcaption>Alternative Energy Source: Wind Power</figcaption></figure>"
];

slides.height = 150;
slides.width = 150;

function fadeOut() {
    "use strict";
    
    masthead.style.opacity = 0;
}

function runSlides() {
    "use strict";
    
    masthead.style.opacity = 1;
    
    if (i > 3) {
        i = 0;
    }
    
    masthead.innerHTML = slides[i];
    i += 1;
    setTimeout(fadeOut, 5000);
}

runSlides();

setInterval(runSlides, 6000);

/*    
-------------------------------------
START CODING REVEAL-HIDE MAIN-CONTENT
------------------------------------- */
    
var buttons = document.querySelectorAll(".btn");

var contents = [
    "<figure><img src=\"./img/geothermal.png\" alt\"geothermal-energy\"> <figcaption>There's geothermal energy - which uses the differential between near-constant temperatures below-ground and temperatures up here to create energy. Because geothermal energy equipment is of necessity buried, it costs a bit more to maintain it. But total costs tend to average around 10 cents a kwh -- similar to wind, and not much more than hydro. But again, a heck of a lot cheaper than solar. Indeed, at the Geysers power plant in California, geothermal energy is sold for as little as 3 cents a kwh.</figcaption></figure>",
    
    "<figure><img src=\"./img/wind-power.png\" alt\"wind-power\"> <figcaption>EIA estimates say that amortized over their lifetime, windmills generate electricity for a cost of just 10 cents a kwh on average - on par with hydro, and far cheaper than solar. Across the ocean, the European Wind Energy Association claims that some of its member projects are generating electricity at a cost of as little as 5 cents a kwh.</figcaption></figure>",
    
    "<figure><img src=\"./img/nuclear.png\" alt\"nuclear-energy\"> <figcaption>Seeing as the nuclear power plants been around since the 1950s, you may not think of nuclear power as being particularly alternative. But it doesn't produce greenhouse gases, and it does produce electricity. And at just 11 cents a kwh to pay for electrons generated by the latest generation of nuclear reactors, it's definitely in the hunt to underprice solar. In France, where they do nuclear power at scale, utility company Electricite de France sells nuclear-generated electricity for about 5 cents a kwh.</figcaption></figure>"
];

var container = document.querySelector(".container");

container.innerHTML = contents[0];

function handleClick(ev) {
    "use strict";
    
    console.log(ev.target.innerHTML);
    
    for (k = 0; k < buttons.length; k += 1) {
        if (buttons[k].hasAttribute("id")) {
            buttons[k].removeAttribute("id");
        }
    }
    if (ev.target.innerHTML === "Solution1") {
        container.innerHTML = contents[0];
    }
    if (ev.target.innerHTML === "Solution2") {
        container.innerHTML = contents[1];
    }
    if (ev.target.innerHTML === "Solution3") {
        container.innerHTML = contents[2];
    }
    
    ev.target.parentNode.setAttribute("id", "active");
}

for (k = 0; k < buttons.length; k += 1) {
    buttons[k].addEventListener("click", handleClick, false);
}


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    